server:
  port: 8008

spring:
  application:
    name: Client-Zuul

#########eureka注册中心设置#######################
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    #服务注册中心的配置内容，指定服务注册中心的位置
    service-url:
      defaultZone: http://dxk:123456@${eureka.instance.hostname}:8001/eureka/
######################## zuul路由设置########################
# url以api-ribbon 开头的会调用client-ribbon服务，以api-fegin 开头的会调用client-fegin服务，
zuul:
  routes:
    api-a:
      path: /api-ribbon/**
      serviceId: Client-Ribbon
    api-b:
      path: /api-fegin/**
      serviceId: Client-Fegin