server:
  port: 8012

spring:
  application:
    name: Client-Fegin

#########eureka注册中心设置#######################
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    #服务注册中心的配置内容，指定服务注册中心的位置
    service-url:
      defaultZone: http://dxk:123456@${eureka.instance.hostname}:8001/eureka/

#Feign是自带断路器的，在D版本的Spring Cloud中，它没有默认打开。需要在配置文件中配置打开它
fegin:
  hystrix:
    enabled: true