#服务注册中心端口
server:
  port: 9001
#应用名称
spring:
  application:
    name: SendEmail-Client
    #邮件
  mail:
      host: smtp.qq.com
      username: 979352276@qq.com
      password: uiqapzsealbfbeia
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enabl: true
              required: true


##########eureka注册中心设置#######################
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    #服务注册中心的配置内容，指定服务注册中心的位置
    service-url:
      defaultZone: http://dxk:123456@${eureka.instance.hostname}:8080/eureka/

  #############邮件相关设置#####################
  #不知道为什么添加这两个属性报错 起不来
#spring:
#  velocity:
#    resource-loader-path: classpath:/templates/
#    charset: UTF-8






